module.exports = {
  'env': {
    'browser': true,
    'commonjs': true,
    'es6': true,
    'node': true,
    'jest': true,
  },
  'parser': '@typescript-eslint/parser',
  'parserOptions': {
    'ecmaFeatures': {
      'jsx': true
    },
    'sourceType': 'module'
  },
  'plugins': [
    'react',
    'react-hooks',
    '@typescript-eslint/eslint-plugin',
    'jest',
    'eslint-plugin-tsdoc'
  ],
  'extends': [
    'eslint:recommended',
    'plugin:react/recommended',
    'plugin:@typescript-eslint/eslint-recommended',
    'plugin:@typescript-eslint/recommended',
  ],
  'rules': {
    '@typescript-eslint/explicit-function-return-type': 'off',
    "eol-last": [2, "always"],
    // 'arrow-parens': ['error', 'as-needed', { requireForBlockBody: true }],
    'block-scoped-var': 'warn',
    'brace-style': ['error', '1tbs', { 'allowSingleLine': true }],
    'camelcase': ['error', {'properties': 'always'}],
    'comma-dangle': ['error', 'only-multiline'],
    'comma-spacing': ['error', { 'before': false, 'after': true }],
    'comma-style': ['error', 'last'],
    'curly': 'error',
    'eqeqeq': 'warn',
    'indent': ['error', 2, { 'SwitchCase': 1 }],
    'jsx-quotes': ['error', 'prefer-double'],
    'keyword-spacing': ['error', { 'before': true, 'after': true }],
    'newline-per-chained-call': ['error', { 'ignoreChainWithDepth': 2 }],
    'no-alert': 'warn',
    'no-array-constructor': 'error',
    'no-console': ['warn', { allow: ['error'] }],
    'no-const-assign': 'error',
    'no-debugger': 'error',
    'no-duplicate-imports': 'error',
    'no-empty': 'warn',
    'no-inline-comments': 'warn',
    'no-loop-func': 'error',
    'no-multi-spaces': 'error',
    'no-new': 'error',
    'no-spaced-func': 'warn',
    'no-trailing-spaces': 'error',
    'no-undefined': 'warn',
    'no-undef': 'error',
    'no-unused-expressions': ['error', { 'allowShortCircuit': true, 'allowTernary': true }],
    'no-unused-vars': 'warn',
    'no-use-before-define': ['error', { 'functions': false }],
    'no-var': 'error',
    'object-curly-spacing': ['warn', 'always'],
    'object-shorthand': 'error',
    'padding-line-between-statements': ['error', 
      { 'blankLine': 'always', 'prev': '*', 'next': 'return' },
      { 'blankLine': 'always', 'prev': ['const', 'let', 'var'], 'next': '*' },
      { 'blankLine': 'any', 'prev': ['const', 'let', 'var'], 'next': ['const', 'let', 'var'] },
      { 'blankLine': 'always', 'prev': 'directive', 'next': '*' },
      { 'blankLine': 'any', 'prev': 'directive', 'next': 'directive' },
    ],
    'semi': [2, 'always'],
    'semi-spacing': ['error', { 'before': false, 'after': true }],
    'space-before-blocks': 'error',
    'space-before-function-paren': ['error', { 'anonymous': 'always', 'named': 'never' }],
    'space-infix-ops': ['error'],
    'switch-colon-spacing': ['error', { 'after': true, 'before': false }],
    'react/jsx-uses-vars': "error",
    'react/jsx-curly-spacing': ['error', 'never'],
    'react/jsx-equals-spacing': ['error', 'never'],
    'react/jsx-no-bind': ['error', {
      'ignoreRefs': true,
      'allowArrowFunctions': false,
      'allowFunctions': false,
      'allowBind': false,
      'ignoreDOMComponents': false,
    }],
    'react/display-name': 'off',
    'react/prop-types': 'off',
    'react/jsx-max-props-per-line': [2, { 'maximum': 1 }],
    'react/jsx-indent-props': [2, 2],
    'strict': 0,
    'react-hooks/rules-of-hooks': 'error',
    'react-hooks/exhaustive-deps': 'warn',
    'tsdoc/syntax': 'warn'
  }
}